db:
  image: mariadb
  command: /bin/bash -c "export TERM=dumb && export MYSQL_ROOT_PASSWORD=password && export MYSQL_DATABASE=shed && ./docker-entrypoint.sh mysqld"
  ports: 
    - "3306:3306"
web:
  build: ./docker_demo
  command: /bin/bash -c "sleep 25 && ./run-django.sh"
  ports:
    - "8000:8000"
    - "9181:9181"
  links:
    - db
